### ISSUE TITLE
Adopt standard Python naming conventions

### ISSUE THREAD

**Issue by varunlakshmanan** [PranavPusarla/Coronavirus-Growth#1]
In several instances, you, @PranavPusarla, have used camel case rather than the Python standard of snake case (separating distinct words with underscores). Please abide by Section 34 of the PEP 8 Style Guide for Python Code, https://www.python.org/dev/peps/pep-0008/, in your future Python endeavors.

**Comment by computer-geek64** [comment]
Please follow standard English conventions @varunlakshmanan, you left an extra space before one of your commas when you were mentioning @PranavPusarla.
